---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: nodejs
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vuejs
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: vuejs
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80